GWHealth/Controllers/FileUploadController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;

namespace GWHealth.Controllers
{

   
    public class FileUploadController : Controller
    {

        static string path = "D:\\GWUploads";
        public FileUploadController()
        {

        }



        [HttpPost]
        public IActionResult Index(IFormFile[] files)
        {           

            // Iterate through uploaded files array
            foreach (var file in files)
            {
                // Extract file name from whatever was posted by browser
                var fileName = path + "\\"  + System.IO.Path.GetFileName(file.FileName);
                
                // If file with same name exists delete it
                if (System.IO.File.Exists( fileName))
                {
                    System.IO.File.Delete(fileName);
                }

                // Create new local file and copy contents of uploaded file
                using (var localFile = System.IO.File.OpenWrite(fileName))
                using (var uploadedFile = file.OpenReadStream())
                {
                    uploadedFile.CopyTo( localFile);
                }
            }
            if (Request.Form["Env"].ToString() != "")
            {             
                
                return RedirectToAction("Dataload", new RouteValueDictionary(new { controller = "Home", action = "Dataload", Id = Request.Form["Env"].ToString() , caller ="Upload" }  ));
            }
            else
            {
                return RedirectToAction("Index", "Home" );

            }           
            
        }
    }
}

GWHealth/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using GWHealth.Models;
using System.DirectoryServices;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using System.Text;
using System.Security.Principal;

namespace GWHealth.Controllers
{

    public class HomeController : Controller
    {

        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {

            return View(new LoginViewModel());

        }

        public IActionResult Privacy()
        {

            LoginViewModel lv = getAuthenticatedModel();
            return View(lv);

        }

        public IActionResult About()
        {
            LoginViewModel lv = getAuthenticatedModel();
            return View(lv);
        }




        public IActionResult SQL(string id, string caller)
        {
            LoginViewModel lv = getAuthenticatedModel();

            if (lv.IsAuthenticated)
            {
                lv.SetActiveEnvirnment(id);

                if (caller == "Upload")
                {
                    ViewBag.Message = "Files successfully uploaded";
                }

                return View("SqlView", lv);
            }
            else
            {
                return View("Index", lv);
            }

        }

        public IActionResult Dataload(string id, string caller)
        {
            LoginViewModel lv = getAuthenticatedModel();

            if (lv.IsAuthenticated)
            {
                lv.SetActiveEnvirnment(id);

                if (caller == "Upload")
                {
                    ViewBag.Message = "Files successfully uploaded";
                }


                return View(lv);
            }
            else
            {
                return View("Index", lv);
            }

        }

        
        [HttpGet]
        public IActionResult Env(string id)
        {

            LoginViewModel lv = getAuthenticatedModel();

            if (lv.IsAuthenticated)
            {
                lv.SetActiveEnvirnment(id);

                return View(lv);
            }
            else
            {
                return View("Index", lv);
            }


        }



        [HttpGet]
        public IActionResult Command(string id)
        {
            LoginViewModel lv = getAuthenticatedModel();

            string[] input = id.Split("%2F");

            if (lv.IsAuthenticated)
            {
                lv.SetActiveEnvirnment(input[0]);

                TCPClient.TCPClient tc = new TCPClient.TCPClient();

                string output = tc.StartClient ( lv.Username , input[1] , input[2]);
                
                ViewBag.Message = input[1] + " successfully Started ---- " + output ;
                tc = null;

                return View("Env" ,lv);
            }
            else
            {
                return View("Index", lv);
            }


        }





        public async Task<IActionResult> MainAsync()
        {
            if (Request.Cookies.Count > 0)
            {

                if (Request.Cookies["Auth"] != null)
                {
                    LoginViewModel lv = getAuthenticatedModel();
                    if (lv.IsAuthenticated)
                    {
                        return View("../Home/Main", lv);
                    }
                    else
                    {
                        return View("Index", lv);
                    }

                }
                string username = Request.Form["Username"];
                string password = Request.Form["Password"];
                if (isAuthenticated(username, password))
                {
                    LoginViewModel lv = new LoginViewModel();

                    string srvr = "LDAP://mfb.zengwcloud.com";
                    DirectoryEntry entry = new DirectoryEntry(srvr, username, password);
                    DirectorySearcher mySearcher = new DirectorySearcher(entry);
                    mySearcher.Filter = "(&(objectClass=user)(anr=" + username + "))";
                    foreach (SearchResult singleADUser in mySearcher.FindAll())
                    {
                        // Debug.WriteLine("The properties of the " + singleADUser.GetDirectoryEntry().Name + " are :");

                        lv.DisplayName = singleADUser.GetDirectoryEntry().Name.Replace("CN=", "");

                        //foreach (string singleAttribute in ((ResultPropertyCollection)singleADUser.Properties).PropertyNames)
                        //{
                        //    Debug.WriteLine(singleAttribute + " = ");
                        //    foreach (Object singleValue in ((ResultPropertyCollection)singleADUser.Properties)[singleAttribute])
                        //    {
                        //        Debug.WriteLine("\t" + singleValue);
                        //    }
                        //}


                    }


                    await HttpContext.SignInAsync("Cookies", getPrincipal(username, lv.DisplayName));
                    lv.Username = entry.Username;
                    lv.IsAuthenticated = true;
                    return View("../Home/Main", lv);
                }
                else
                {
                    //Password Failed
                    await HttpContext.SignOutAsync();
                    return View("Error", new LoginViewModel { RequestId = "404" ,  });
                }
            }
            else
            {

                LoginViewModel lv = getAuthenticatedModel();

                if (lv.IsAuthenticated)
                {
                    return View("../Home/Main", lv);
                }
                else
                {
                    return View("Index", lv);
                }



            }

        }

        private LoginViewModel getAuthenticatedModel()
        {
            if (HttpContext.User.Claims.ToList().Count > 0)
            {
                var userId = HttpContext.User.Claims.FirstOrDefault().Value;
                var DisplayName = HttpContext.User.Claims.ToList()[1].Value;
                LoginViewModel lv = new LoginViewModel();
                lv.Username = userId;
                lv.DisplayName = DisplayName;
                lv.IsAuthenticated = true;
                return lv;
            }
            else
            {
                return new LoginViewModel();
            }

        }

        private ClaimsPrincipal getPrincipal(string username, string displayname)
        {
            var claims = new List<Claim>
                    {
                     new Claim( "User", username  ) ,
                     new Claim( "DisplayName", displayname )
                     };

            var userIdentity = new ClaimsIdentity(claims, "User");
            ClaimsPrincipal principal = new ClaimsPrincipal(userIdentity);

            return principal;

        }

        private bool isAuthenticated(string username, string password)
        {
            string srvr = "LDAP://mfb.zengwcloud.com";
            bool authenticated = false;

            try
            {
                DirectoryEntry entry = new DirectoryEntry(srvr, username, password);
                object nativeObject = entry.NativeObject;
                authenticated = true;
            }
            catch (DirectoryServicesCOMException cex)
            {
                return false;

            }
            catch (Exception ex)
            {
                return false;

            }

            return authenticated;
        }

        


        public async Task<IActionResult> SignOutAsync()
        {

            await HttpContext.SignOutAsync();

            LoginViewModel lv = new LoginViewModel();
            return View(lv);
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new LoginViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GWHealth/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}



<div class="jumbotron">
    <h1>@ViewData["Title"]</h1>
    <p>...</p>
    <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>
</div>

GWHealth/Views/Home/DataLoad.cshtml
@model LoginViewModel
@{
    ViewData["Title"] = "Admin-Load";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Home</a></li>
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Main">Main</a></li>
        <li class="breadcrumb-item"><a asp-controller="Home"  asp-action="Env" asp-route-id=@Model.ActiveEnvirnment.Name >@Model.ActiveEnvirnment.Name</a></li>        
        <li class="breadcrumb-item active" aria-current="page">Data Load</li>
    </ol>
</nav>

<div class="jumbotron">
    <div class="container">
        <div class="row">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Size</th>
                        <th scope="col">Type</th>
                        <th scope="col">Description</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var item in Model.GWDataFiles())
                    {
                        <tr>
                            <th scope="row">@item.Name </th>
                            <td>@item.Size</td>
                            <td>@item.Path</td>
                            <td>@item.Description</td>
                        </tr>

                    }

                </tbody>
            </table>
        </div>

    </div>
</div>




<div class="container">
    <div class="row">

        <form method="post" asp-controller="FileUpload" asp-action="Index" enctype="multipart/form-data">
            <input type="file" name="files" />
            <input type="hidden" name="env" value=@Model.ActiveEnvirnment.Name />
            <button type="submit">Upload</button>
        </form>

        @if (ViewBag.Message != null)
        {
            <div class="alert alert-success" style="margin-top:20px">
                @ViewBag.Message
            </div>
        }

    </div>

</div>

GWHealth/Views/Home/Env.cshtml
@model LoginViewModel

@{
    ViewData["Title"] = "Env";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Home</a></li>
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Main">Main</a></li>
        <li class="breadcrumb-item active" aria-current="page">@Model.ActiveEnvirnment.Name</li>

    </ol>
</nav>

<div class="container">
    <div class="row">
        <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">

            <div class="btn-group mr-2" role="group" aria-label="Second group">
                <a href="/Home/Dataload/@Model.ActiveEnvirnment.Name" class="btn btn-primary">Data Load</a>
            </div>

            <div class="btn-group mr-2" role="group" aria-label="Second group">
                <a href="/Home/SQL/@Model.ActiveEnvirnment.Name" class="btn btn-primary">SQL View</a>
            </div>

            <div class="btn-group mr-2" role="group" aria-label="Second group">
                <a href="#" class="btn btn-primary">Release History</a>
            </div>

            <div class="btn-group mr-2" role="group" aria-label="Second group">
                <a href="#" class="btn btn-primary">Health</a>
            </div>
        </div>

    </div>

</div>

<div class="container">
    <div class="m-1 p-1"></div>
    @if (@Model.ActiveEnvirnment.GWMachines != null)
    {


        @if (Model.ActiveEnvirnment.IsClusterd)
        {
            <div class="m-1 p-1"></div>
            <div class="row">
                @foreach (var machine in @Model.ActiveEnvirnment.GWMachines)
                {
                    if (@machine.isBatch)
                    {
                        <div class="col">
                            <div class="card text-center" style="width: 12rem;">
                                <div class="card-body">

                                    <button type="button" onclick="aboutclick('  @machine.Name ')" class="btn btn-outline-primary" data-toggle="modal" data-target="#exampleModalLong">
                                        <img src="~/Server.png" />
                                    </button>


                                    <p class="card-text">@machine.Name</p>

                                    <p class="card-text">@machine.Description</p>
                                    <p class="card-text">@machine.IPAddress</p>

                                    <a href='javascript:;' onclick='linkclick(" @machine.PublicUrl ");' class="btn btn-primary btn-sm active" role="button" aria-pressed="true">Public</a>
                                    <a href='javascript:;' onclick='linkclick(" @machine.Privateurl");' class="btn btn-secondary btn-sm active" role="button" aria-pressed="true">Private</a>

                                    <p class="card-text">DB: @machine.DatabaseServer</p>
                                    <p class="card-text">Build On: @machine.BulildDate</p>
                                    <p class="card-text">Depl On: @machine.DeploydDate</p>


                                    <a asp-controller="Home" class="btn btn-primary" asp-action="Command" asp-route-id="@Model.ActiveEnvirnment.Name/Build/@machine.IPAddress">B</a>
                                    <a asp-controller="Home" class="btn btn-primary" asp-action="Command" asp-route-id="@Model.ActiveEnvirnment.Name/Deploy/@machine.IPAddress">D</a>
                                    <a asp-controller="Home" class="btn btn-primary" asp-action="Command" asp-route-id="@Model.ActiveEnvirnment.Name/Restart/@machine.IPAddress">R</a>
                                    <a asp-controller="Home" class="btn btn-primary" asp-action="Command" asp-route-id="@Model.ActiveEnvirnment.Name/Log/@machine.IPAddress">L</a>

                                </div>
                            </div>
                        </div>
                    }
                }
            </div>
            <div class="m-1 p-1"></div>
            <div class="row">
                @foreach (var machine in @Model.ActiveEnvirnment.GWMachines)
                {
                    if (!@machine.isBatch)
                    {
                        <div class="col">
                            <div class="card text-center" style="width: 12rem;">
                                <div class="card-body">

                                    <button type="button" onclick="aboutclick('  @machine.Name ')" class="btn btn-outline-primary" data-toggle="modal" data-target="#exampleModalLong">
                                        <img src="~/Server.png" />
                                    </button>
                                    <p class="card-text">@machine.Name</p>

                                    <p class="card-text">@machine.Description</p>
                                    <p class="card-text">@machine.IPAddress</p>
                                    <a href='javascript:;' onclick='linkclick(" @machine.PublicUrl ");' class="btn btn-primary btn-sm active" role="button" aria-pressed="true">Public</a>

                                    <a href='javascript:;' onclick='linkclick(" @machine.Privateurl");' class="btn btn-secondary btn-sm active" role="button" aria-pressed="true">Private</a>

                                    <p class="card-text">DB: @machine.DatabaseServer</p>
                                    <p class="card-text">Build On: @machine.BulildDate</p>
                                    <p class="card-text">Depl On: @machine.DeploydDate</p>

                                    <a asp-controller="Home" class="btn btn-primary" asp-action="Command" asp-route-id="@Model.ActiveEnvirnment.Name/Build/@machine.IPAddress">B</a>
                                    <a asp-controller="Home" class="btn btn-primary" asp-action="Command" asp-route-id="@Model.ActiveEnvirnment.Name/Deploy/@machine.IPAddress">D</a>
                                    <a asp-controller="Home" class="btn btn-primary" asp-action="Command" asp-route-id="@Model.ActiveEnvirnment.Name/Restart/@machine.IPAddress">R</a>
                                    <a asp-controller="Home" class="btn btn-primary" asp-action="Command" asp-route-id="@Model.ActiveEnvirnment.Name/Log/@machine.IPAddress">L</a>

                                </div>
                            </div>
                        </div>
                    }
                }
            </div>

        }
        else
        {
            <div class="m-1 p-1"></div>
            <div class="row">
                @foreach (var machine in @Model.ActiveEnvirnment.GWMachines)
                {
                    <div class="col">
                        <div class="card text-center " style="width: 12rem;">
                            <div class="card-body">
                                <button type="button" onclick="aboutclick('  @machine.Name ')" class="btn btn-outline-info">
                                    <img src="~/Server.png" />
                                </button>

                                <p class="card-text">@machine.Name</p>

                                <p class="card-text">@machine.Description</p>
                                <p class="card-text">@machine.IPAddress</p>

                                <a href='javascript:;' onclick='linkclick(" @machine.PublicUrl ");' class="btn btn-primary btn-sm active" role="button" aria-pressed="true">Public</a>

                                <a href='javascript:;' onclick='linkclick(" @machine.Privateurl");' class="btn btn-secondary btn-sm active" role="button" aria-pressed="true">Private</a>
                                

                                <p class="card-text">DB: @machine.DatabaseServer</p>
                                <p class="card-text">Build On: @machine.BulildDate</p>
                                <p class="card-text">Depl On: @machine.DeploydDate</p>

                                <a asp-controller="Home" class="btn btn-primary" asp-action="Command" asp-route-id="@Model.ActiveEnvirnment.Name/Build/@machine.IPAddress">B</a>
                                <a asp-controller="Home" class="btn btn-primary" asp-action="Command" asp-route-id="@Model.ActiveEnvirnment.Name/Deploy/@machine.IPAddress">D</a>
                                <a asp-controller="Home" class="btn btn-primary" asp-action="Command" asp-route-id="@Model.ActiveEnvirnment.Name/Restart/@machine.IPAddress">R</a>
                                <a asp-controller="Home" class="btn btn-primary" asp-action="Command" asp-route-id="@Model.ActiveEnvirnment.Name/Log/@machine.IPAddress">L</a>

                            </div>
                        </div>
                    </div>

                }
            </div>

        }



    }
    else
    {
        <div class="alert alert-danger" role="alert">
            There are no machines
        </div>
    }

</div>


@if (Model.ActiveEnvirnment.IsClusterd)
{
    <div class="alert alert-primary" role="alert">
        This is clusterd Env
    </div>

}



@if (ViewBag.Message != null)
{
    <div class="alert alert-success" style="margin-top:20px">
        @ViewBag.Message
    </div>
}


<!-- Modal -->
<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">About Page</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div id="modalbody" class="modal-body">
                <p> Lot of Content </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<div id="grid"></div>
@section scripts{
    <script>

        function aboutclick(str) {

            var strUrl = '/API/About?envname=' + str ;
            jQuery.ajax({
                url: strUrl,
                success: function (html) {                   
                    
                    $("#modalbody").html(html);

                    $('#exampleModalLong').modal({ show: true });
                },
                async: false
            });           

        }


          function linkclick(str) {
           window.open(str); 
        }

    </script>
}

GWHealth/Views/Home/Index.cshtml
@model LoginViewModel

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <div onclick="putlog();">
        @DateTime.Now
    </div>
    <div class="m-5 pl-1 pt-2 pb-5 " >

        <form asp-action="Main" method="post" >
            <input class="align-middle" type="text" asp-for=Username id="Username" name="Username">
            <input class="align-middle" type="password" asp-for=Password id="Password" name="Password" />
            <button class="align-middle btn btn-primary" type="submit" >Login</button>
        </form>
    </div>
    <div >
        <img src="~/DevOps.png" />
    </div>

</div>


<script>

    function putlog() {
       
        var s= document.getElementById("Username");
        s.value = 'kipi'

        s= document.getElementById("Password");
        s.value = 'Temp@1234'
        


    }

</script>

GWHealth/Views/Home/SignOut.cshtml
@{
    ViewData["Title"] = "SignOut";
}
<h1>@ViewData["Title"]</h1>


<p>Thanks </p>

GWHealth/Views/Home/SqlView.cshtml
@model LoginViewModel
@{
    ViewData["Title"] = "SQL";
}

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Home</a></li>
            <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Main">Main</a></li>            
            <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Env" asp-route-id=@Model.ActiveEnvirnment.Name>@Model.ActiveEnvirnment.Name</a></li>
            <li class="breadcrumb-item active" aria-current="page">SQL View</li>
        </ol>
    </nav>



    <div class="container">
        <div class="row">
            <div class="alert alert-success" style="margin-top:20px">
                This view is provided only for making select statements. Delete, Drop statements are not allowed.
            </div>
        </div>

        <div class="row">
            <form>
                <div class="form-group">
                    <label for="inputSQL">SQL</label>
                    <input   type="text" class="col-12" id="inputSQL" placeholder="SQL">
                </div>
                <button type="submit" class="btn btn-primary">Execute</button>
            </form>

        </div>

        <div class="row">
            <div class="col-xl-12" style="margin-top:20px">
                Result
            </div>
        </div>



    </div>


 